editor = "nvim"
blinking_cursor = true
performance = "High"
use-fork = true
line-height = 1.0
theme = "onedark"
padding-x = 0.0
cursor = "▇"
ignore-selection-foreground-color = true
working-dir = "/home/geg/Desktop"
hide-cursor-when-typing = false

[keyboard]
use-kitty-keyboard-protocol = true
disable-ctlseqs-alt = false

[navigation]
mode = "CollapsedTab"
clickable = true
use-current-path = true
use-terminal-title = true
color-automation = [
  { program = "nvim", color = "#00b952" },
  { program = "vim", color = "#019331" },
  { program = "docker", color = "#1d63ed" },
  { program = "npm", color = "#ea2039" },
  { program = "node", color = "#ea2039" },
  { program = "cargo", color = "#dea584" },
  { program = "python", color = "#3572a5" },
  { program = "pip", color = "#3572a5" },
  { program = "pipx", color = "#3572a5" },
]

[window]
opacity = 1.0
width = 600
height = 400
mode = "Windowed"

[shell]
program = ""
args = ["--login"]

[fonts]
size = 18.0
family = "Dejavu Sans Mono"
